spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/user?serverTimezone=GMT&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always